version: '3.9'

services:
  web:
    build: .
    container_name: brave-gnu-world
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: brave-gnu-world-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
