services:
  web:
    build: .
    container_name: brave-gnu-world
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0

  mongo:
    image: mongo:4.4
    container_name: brave-gnu-world-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
